
GENERAL:
  seed: 2021
  log_path: /home/ny/gene_multimodal/TRIPLEX/logs
  
TRAINING:
  num_k: 5
  learning_rate: 1.0e-4
  num_epochs: 5
  monitor: PearsonCorrCoef
  mode: max
  early_stopping:
    patience: 20
  lr_scheduler:
    patience: 10
    factor: 0.1
  
MODEL:
  model_name: his_to_gene 
  num_outputs: 785

DATA:
  data_dir: /home/ny/gene_multimodal/TRIPLEX/input/ST/andersson
  output_dir: /home/ny/gene_multimodal/TRIPLEX/output/pred/ST/andersson
  dataset_name: HisToGeneDataset
  gene_type: 'mean'
  num_genes: 1000
  num_outputs: 785
  cpm: True
  smooth: True
  
  train_dataloader:
        batch_size: 128
        num_workers: 8
        pin_memory: False
        shuffle: True

  test_dataloader:
      batch_size: 1
      num_workers: 4
      pin_memory: False
      shuffle: False